In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import re
#to access our implemented ML functions
%load_ext autoreload
%autoreload 2


In [105]:
from implementations import *

In [116]:
Energy_range = [0.1, 0.2, 0.3, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0]
data_path = data_file(20.0)

In [117]:
df = build_df(data_path)

In [118]:
df[-17:-1]

X(mm) Y(mm)  \
*                                                                         
:                                                            73.9  82.4   
:----------------------------------------------...  EndOf2ndaries  Info   
23                                                           75.8    82   
:-----                                                       List    of   
:                                                            75.8    82   
:----------------------------------------------...  EndOf2ndaries  Info   
24                                                           78.2  82.3   
25                                                           79.7  82.2   
26                                                           80.5  82.1   
27                                                           81.2  81.8   
28                                                           81.7    82   
29                                                             82  82.3   
30                                                           82.3  82.4   
31                                                           82.3  82.7   
32                                                           82.4  82.7   
33                                                           82.3  82.6   

                                                              Z(mm)      DX  \
*                                                                             
:                                                               112   0.982   
:----------------------------------------------...  ---------------     NaN   
23                                                              112   0.965   
:-----                                                     2ndaries       -   
:                                                               112   0.772   
:----------------------------------------------...  ---------------     NaN   
24                                                              112   0.758   
25                                                              111   0.474   
26                                                              109   0.568   
27                                                              108   0.536   
28                                                              107   0.474   
29                                                              107   0.553   
30                                                              106   0.165   
31                                                              106  0.0394   
32                                                              107  -0.221   
33                                                              107   0.981   

                                                               DY       DZ  \
*                                                                            
:                                                         -0.0889    0.165   
:----------------------------------------------...            NaN      NaN   
23                                                         0.0985   -0.242   
:-----                                              #SpawnInStep=  1(Rest=   
:                                                          -0.155    0.616   
:----------------------------------------------...            NaN      NaN   
24                                                        -0.0281   -0.652   
25                                                        -0.0403   -0.879   
26                                                         -0.292    -0.77   
27                                                          0.214   -0.817   
28                                                          0.453   -0.755   
29                                                          0.262   -0.791   
30                                                          0.946    -0.28   
31                                                         -0.113    0.993   
32                                    

In [119]:
df[:10]

X(mm)  Y(mm)  \
*                                                                          
Step#                                                       X(mm)  Y(mm)   
0                                                               0    100   
1                                                            4.12   99.8   
:-----                                                       List     of   
:                                                            4.12   99.8   
:----------------------------------------------...  EndOf2ndaries   Info   
2                                                            8.26   99.1   
:-----                                                       List     of   
:                                                            8.26   99.1   
:----------------------------------------------...  EndOf2ndaries   Info   

                                                              Z(mm)     DX  \
*                                                                            
Step#                                                         Z(mm)     DX   
0                                                               100      0   
1                                                               100  0.987   
:-----                                                     2ndaries      -   
:                                                               100  0.802   
:----------------------------------------------...  ---------------    NaN   
2                                                               100  0.974   
:-----                                                     2ndaries      -   
:                                                               100  0.506   
:----------------------------------------------...  ---------------    NaN   

                                                               DY       DZ  \
*                                                                            
Step#                                                          DY       DZ   
0                                                               0        0   
1                                                           -0.16  -0.0122   
:-----                                              #SpawnInStep=  1(Rest=   
:                                                           0.592   0.0804   
:----------------------------------------------...            NaN      NaN   
2                                                          -0.227  -0.0181   
:-----                                              #SpawnInStep=  1(Rest=   
:                                                           0.811   -0.293   
:----------------------------------------------...            NaN      NaN   

                                                    KinE(MeV)  dE(MeV)  \
*                                                                        
Step#                                               KinE(MeV)  dE(MeV)   
0                                                          20        0   
1                                                        18.4    0.563   
:-----                                               0,Along=  0,Post=   
:                                                        1.07       e-   
:----------------------------------------------...        NaN      NaN   
2                                                        17.6    0.621   
:-----                                               0,Along=  0,Post=   
:                                                       0.119       e-   
:----------------------------------------------...        NaN      NaN   

                                                    StepLeng     TrackLeng  \
*                                                                            
Step#                                               StepLeng     TrackLeng   
0                                                          0             0   
1                                                       4.12          4.

## Building of clean dataframe

In [185]:
df_clean = clean_df(df)

In [186]:
df_clean.head(10)

index  X(mm)  Y(mm)  Z(mm)     DX     DY       DZ  KinE(MeV)  dE(MeV)  \
0      0   0.00  100.0  100.0  0.000  0.000  0.00000      20.00   0.0000   
1      1   4.12   99.8  100.0  0.987 -0.160 -0.01220      18.40   0.5630   
2      2   8.26   99.1  100.0  0.974 -0.227 -0.01810      17.60   0.6210   
3      3  12.90   98.2  100.0  0.983 -0.184  0.00546      16.80   0.7790   
4      4  14.60   97.8  100.0  0.937 -0.331  0.10700      11.60   0.3110   
5      5  19.00   96.4  101.0  0.834 -0.449  0.32000      10.90   0.7010   
6      6  19.50   96.1  101.0  0.829 -0.444  0.34000      10.60   0.0663   
7      7  23.20   94.5  103.0  0.865 -0.263  0.42800       9.95   0.7000   
8      8  27.50   93.3  105.0  0.706 -0.146  0.69200       9.18   0.7700   
9      9  30.50   92.6  109.0  0.597 -0.067  0.80000       8.38   0.8000   

   StepLeng  X(mm)_s  Y(mm)_s  Z(mm)_s   DX_s   DY_s    DZ_s  Kin(MeV)_s  \
0     0.000     0.00      0.0      0.0  0.000  0.000  0.0000       0.000   
1     4.120     4.12     99.8    100.0  0.802  0.592  0.0804       1.070   
2     4.220     8.26     99.1    100.0  0.506  0.811 -0.2930       0.119   
3     4.780     0.00      0.0      0.0  0.000  0.000  0.0000       0.000   
4     1.690    14.60     97.8    100.0  0.987  0.133 -0.0869       4.890   
5     4.750     0.00      0.0      0.0  0.000  0.000  0.0000       0.000   
6     0.593    19.50     96.1    101.0  0.801 -0.496  0.3350       0.226   
7     4.350     0.00      0.0      0.0  0.000  0.000  0.0000       0.000   
8     5.260     0.00      0.0      0.0  0.000  0.000  0.0000       0.000   
9     4.890     0.00      0.0      0.0  0.000  0.000  0.0000       0.000   

  name_s  
0      0  
1     e-  
2     e-  
3      0  
4     e-  
5      0  
6  gamma  
7      0  
8      0  
9      0

In [187]:
X, y = creation_array(df_clean)

In [193]:
((y[:,2] < -1) & (y[:,2] > 1)).sum()

0

### Is it always Spawn_in_step == 1 ?

In [188]:
for E in Energy_range:
    df_check = clean_df(build_df(data_file(E)))
    Spawn_in_step = df_check[df_check.index == ':-----']['DZ']
    Spawn_in_step = Spawn_in_step.str.replace('(','',regex=True).str.replace('Rest=','',regex=True).astype('int')
    print('For Energy ', E, ' we have : ',Spawn_in_step[Spawn_in_step != 1].sum(), ' interactions that produce more than 1 one particule')

KeyboardInterrupt: 

In [11]:
#Try to build the input and outputs corresponding to build a ML model

In [18]:
df_clean.head()

index     DX       DY      DZ KinE(MeV)  dE(MeV) StepLeng ProcName DX_s  \
0     0      0        0       0       0.1        0        0      msc  NaN   
1     1  0.995  -0.0748  0.0695     0.098  0.00196    0.048      msc  NaN   
2     2  0.975    0.196   0.101    0.0969  0.00111   0.0473      msc  NaN   
3     3  0.955   0.0481   0.293    0.0944  0.00257   0.0499      msc  NaN   
4     4  0.917   -0.171   0.361    0.0927  0.00163   0.0482      msc  NaN   

  DY_s DZ_s Kin(MeV)_s name_s  
0  NaN  NaN        NaN    NaN  
1  NaN  NaN        NaN    NaN  
2  NaN  NaN        NaN    NaN  
3  NaN  NaN        NaN    NaN  
4  NaN  NaN        NaN    NaN

In [169]:
((df_clean['DX']*df_clean['DX'] + df_clean['DY']*df_clean['DY'] + df_clean['DZ']*df_clean['DZ']).min())

0.0

In [19]:
np_data = df_clean.to_numpy()

In [21]:
np_data[0:5, 1]

array(['0', '0.995', '0.975', '0.955', '0.917'], dtype=object)

In [16]:
np_data.shape[0]

397557

In [49]:
data_int = []
for idx, data_x in enumerate(np_data[0:20, 0:7]) :
    print(data_x.astype(float))
np_data[0:20, 8]

[0.  0.  0.  0.  0.1 0.  0. ]
[ 1.       0.995   -0.0748   0.0695   0.098    0.00196  0.048  ]
[2.00e+00 9.75e-01 1.96e-01 1.01e-01 9.69e-02 1.11e-03 4.73e-02]
[3.00e+00 9.55e-01 4.81e-02 2.93e-01 9.44e-02 2.57e-03 4.99e-02]
[ 4.00e+00  9.17e-01 -1.71e-01  3.61e-01  9.27e-02  1.63e-03  4.82e-02]
[ 5.00e+00  8.76e-01 -1.13e-01  4.68e-01  9.11e-02  1.66e-03  4.29e-02]
[ 6.00e+00  8.15e-01 -1.46e-01  5.61e-01  8.88e-02  2.27e-03  5.16e-02]
[ 7.00e+00  5.12e-01 -3.24e-01  7.95e-01  8.74e-02  1.37e-03  4.62e-02]
[ 8.00e+00  7.23e-01 -6.19e-01  3.08e-01  8.66e-02  8.12e-04  4.41e-02]
[ 9.00e+00  7.17e-01 -5.46e-01  4.32e-01  8.49e-02  1.72e-03  4.40e-02]
[ 1.00e+01  5.94e-01 -5.62e-01  5.76e-01  8.29e-02  2.03e-03  4.38e-02]
[ 1.10e+01  6.77e-01 -5.31e-01  5.09e-01  8.12e-02  1.66e-03  4.26e-02]
[ 1.20e+01  8.81e-01 -4.26e-01  2.07e-01  7.85e-02  2.75e-03  4.49e-02]
[ 1.30e+01  6.57e-01 -6.88e-01  3.09e-01  7.67e-02  1.78e-03  4.17e-02]
[ 1.40e+01  6.00e-01 -7.44e-01  2.96e-01  7.35e-02  3.1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan], dtype=object)

In [170]:
X, y = creation_array(df_clean)

Exception: Not a good type of particle

In [139]:
a = [0,1,2]
a+=[0,0,0]
print(a)

[0, 1, 2, 0, 0, 0]


In [118]:
X[0:5]

array([[0.       , 0.1      , 0.       , 0.       , 1.       ],
       [0.       , 0.098    , 0.00196  , 0.048    , 1.       ],
       [0.9624837, 0.0969   , 0.00111  , 0.0473   , 1.       ],
       [0.9701456, 0.0944   , 0.00257  , 0.0499   , 1.       ],
       [0.9732829, 0.0927   , 0.00163  , 0.0482   , 1.       ]])

In [122]:
y[:,1].shape

(377557,)

In [157]:
y[0:20,2]

array([0.        , 0.99787882, 0.99911117, 0.98255922, 0.964317  ,
       0.999542  , 0.979377  , 0.945264  , 0.984864  , 0.98728175,
       1.00033268, 0.98281261, 0.9714737 , 0.9749054 , 0.996074  ,
       0.969687  , 0.916352  , 0.947204  , 0.983322  , 0.934404  ])

In [114]:
print((y[:,3]==1).sum())

21406


In [ ]:
#Test d'implémenter une méthode de ML sur le premier fichier

In [201]:
y[0:10,]

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 4.12000000e+00,  5.63000000e-01,  9.97878820e-01,
         1.00000000e+00,  4.12000000e+00,  9.98000000e+01,
         1.00000000e+02,  8.02000000e-01,  5.92000000e-01,
         8.04000000e-02,  1.07000000e+00],
       [ 4.22000000e+00,  6.21000000e-01,  9.99111174e-01,
         1.00000000e+00,  8.26000000e+00,  9.91000000e+01,
         1.00000000e+02,  5.06000000e-01,  8.11000000e-01,
        -2.93000000e-01,  1.19000000e-01],
       [ 4.78000000e+00,  7.79000000e-01,  9.82559220e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.69000000e+00,  3.11000000e-01,  9.64317000e-01,
         1.00000000e+00,  1.46000000e+01,  9.78000000e+01,
  

In [155]:
w_, loss = least_squares(y[:,1], X)

In [216]:
y_tr = y[0:540781,:]
X_tr = X[0:540781,:]

y_te = y[540782:-1,:]
X_te = X[540782:-1,:]



In [214]:
w_lololo = least_squares(y_tr[:,2], X_tr)[0]

In [215]:
compute_loss(y_te[:,2], X_te, w_lololo)

0.040317391703877416

In [219]:
for i in range(11):
    #model : 
    w_lololo = least_squares(y_tr[:,i], X_tr)[0]
    loss = compute_loss(y_te[:,i], X_te, w_lololo)
    print("loss pour le output {it} : {l}".format(it = i, l = loss ))

loss pour le output 0 : 1.67263460973168
loss pour le output 1 : 0.04238150683892519
loss pour le output 2 : 0.040317391703877416
loss pour le output 3 : 0.17853489929743627
loss pour le output 4 : 289.16544129035293
loss pour le output 5 : 994.4161076859497
loss pour le output 6 : 990.5666424012483
loss pour le output 7 : 0.04533978483810266
loss pour le output 8 : 0.05025247877559047
loss pour le output 9 : 0.050687929890355934
loss pour le output 10 : 0.17385375200817627


In [194]:
y_tr = y[0:540781,:]
X_tr = X[0:540781,:]

y_te = y[540782:-1,:]
X_te = X[540782:-1,:]



w_dist, loss_dist = least_squares(y[:,0], X)
print("Loss for the distance : {loss} \n".format(loss = loss_dist))


w_E, loss_E = least_squares(y[:,1], X)
print("Loss for the delta_E : {loss} \n".format(loss = loss_E))

w_cos, loss_cos = least_squares(y[:,2], X)
print("Loss for the cos_teta : {loss} \n".format(loss = loss_cos))

w_Q, loss_Q = least_squares(y[:,3], X)
print("Loss for the Q : {loss} \n".format(loss = loss_Q))

Loss for the distance : 1.6676852574310197 

Loss for the delta_E : 0.04226193760615774 

Loss for the cos_teta : 0.04059971401577405 

Loss for the Q : 0.1790071493721218 

